### ISSUE TITLE
Not finding Arxiv articles

### ISSUE THREAD

**Issue by jluttine** [aroig/metadata-sources#1]
I'm not able to find metadata from arxiv. This is the article: https://arxiv.org/abs/1703.10593

These are some metadata fields I have filled:
Title: `Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks`
Authors: `Jun-Yan Zhu & Taesung Park & Phillip Isola & Alexei A. Efros`

The metadata download finds nothing and gives the following output:
```
calibre, version 3.15.0
ERROR: No matches found: <p>Failed to find any books that match your search. Try making the search <b>less specific</b>. For example, use only the author's last name and a single distinctive word from the title.<p>To see the full log, click "Show details".

Running identify query with parameters: 
{u'authors': [u'Jun-Yan Zhu', u'Taesung Park', u'Phillip Isola', u'Alexei A. Efros'], u'identifiers': {}, u'timeout': 30, u'title': u'Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks'} 
Using plugins: Arxiv (1, 3, 0) 
The log from individual plugins is below 

****************************** Arxiv (1, 3, 0) ****************************** 
Found 0 results 
Downloading from Arxiv took 1.95187401772 

******************************************************************************** 
The identify phase took 2.00 seconds 
The longest time (1.951874) was taken by: Arxiv 
Merging results from different sources and finding earliest  publication dates from the worldcat.org service 
We have 0 merged results, merging took: 0.00 seconds 
```

Any ideas what's wrong?

Also, is it possible to download arxiv metadata by just providing a direct link to the page or by giving its ID (in this case 1703.10593)?

**Comment by aroig** [comment]
If you manually add `arxiv:1703.10593v4` in the Ids field for the document, then the arxiv metadata source will find the metadata for that document. Otherwise it does a search for title and author, which may not be reliable.

If you want to automatically retrieve the metadata, combine it with this [pdf metadata reader](https://github.com/aroig/metadata-readers). If you replace Calibre's default PDF reader plugin with this one, then when you add an arxiv document, the arxiv ID will be automatically filled into the IDs field.

**Comment by aroig** [comment]
By the way, I still use those two plugins, but I haven't touched them in ages. Maybe there are better options by now.

**Comment by jluttine** [comment]
Wow, thanks! It works now! :+1:

**Comment by jluttine** [comment]
PS. Didn't find any other alternatives by googling "calibre arxiv".

**Comment by jluttine** [comment]
One more question: Is there some convenient way to add articles from Arxiv to Calibre? I go to Arxiv and find an interesting and want to add it to my Calibre collection. As far as I know, I need to download the PDF, add it to Calibre and download metadata. Can I add a book just by copying the URL or Arxiv ID somewhere and it would fetch the PDF (and the metadata)?

**Comment by aroig** [comment]
Not that I know of. This is what I do: download the PDFs from arxiv, add them to calibre, and then download the metadata manually (can be done in bulk for several articles). What you suggest would be cool, but I haven't needed it enough to spend the time writing another plugin for it...

**Comment by jluttine** [comment]
Yep, thanks! To make it super-cool, it would need to be a plugin for Firefox (or whatever browser) too. So I could have a button in my toolbar and I click it when I'm on the article page in Arxiv. And boom, it would send the article for Calibre which would do then its magic automatically. That's how I do it with Zotero and it's so convenient that it's just fun. Just one click and it's done.
